# Nombre de la aplicación
spring.application.name=springboot-web
# Puerto donde corre el servidor
server.port=8080
# Valores personalizados que tú defines para usarlos en tu código
config.code=12345
config.username=jonas
config.message=Hello World
# lista de datos separada por comas
config.listOfValues=1,2,3,4,5