# Valores personalizados que tú defines para usarlos en tu código
config.code=12345
config.username=jonas
config.message=Hola desde el segundo archivo de properties
config.listOfValues=hola,que,tal,como,estas
config.valuesMap={product: 'Cpu Intel Core i7 12th', description: 'Alder Lake, 12 core, a 5 Ghz', price: '1234'}